# Header
menu:
  首页: /
  导览: /series/
  简历: /about/
  好玩: /fun/
  大神: /leading/
  观点: /sayingview/
  项目: https://github.com/hscspring
  存档: /archives/

# Content
excerpt_link: More
prev: Prev
next: Next

# Sidebar
widgets:
- search
- recent_posts
- category
- tagcloud
- music
# - tag

# Gitalk
gitalk:
  id: 0eb512031083d6e7edfb
  secret: e830808995dd813ca26fed50573760963457da37

# Miscellaneous
# google_analytics:
# favicon:
# rss: /atom.xml
